### ISSUE TITLE
How do deodex a whole /system partition?

### ISSUE THREAD

**Issue by kozross** [aureljared/simple-deodexer#3]
I've got a dump of /system, and I want to deodex everything in it. How can I do that with your script, if it's possible?

**Comment by jareddantis** [comment]
Copy the folders `app`, `priv-app`, and `framework` into the `triage` folder and run the script.

**Comment by kozross** [comment]
I did that, and the script gives me ``No apps to deodex``, even though there are definitely odex files around.

**Comment by jareddantis** [comment]
Strange. Can you provide me with the system dump?

**Comment by kozross** [comment]
[Please find the relevant folders here][1]. It's a large file (~1.3G), even zipped at ``-9``, so apologies in advance.

[1]: https://transfer.sh/6fp7f/imgdump.zip

**Comment by jareddantis** [comment]
No worries, will take a look at this as soon as I can. Happy new year!

**Comment by jareddantis** [comment]
What Android API level is this system dump?

**Comment by kozross** [comment]
22 I believe.

**Comment by jareddantis** [comment]
OK, I made a couple of commits that _should_ help with Lollipop support, but when I tried it with your dump, not everything gets deodexed. For example, when deodexing `framework/aspectjrt.jar`:

```
01-07 16:27:45:953 Output to triage/framework/aspectjrt.odex
01-07 16:27:47:571 Analysis error in class=Lcom/lge/org/bouncycastle/asn1/ua/DSTU4145NamedCurves; method=<clinit>
Method: Lcom/lge/org/bouncycastle/asn1/ua/DSTU4145NamedCurves;-><clinit>()V
Near line: 23 (address 38)
Instructions: 
 [17] iput-wide-volatile regA=0 regB=1
 [18] move regA=0 regB=0
 [19] move-result-object regA=1 <-----
 [20] iput-wide-volatile regA=0 regB=2
 [21] return-wide regA=0

01-07 16:27:47:573 org.jf.dexlib2.analysis.AnalysisException: move-result-object must occur after an invoke-*/fill-new-array instruction
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeMoveResult(MethodAnalyzer.java:1333)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:859)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:259)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:190)
    at org.rh.smaliex.DexUtil$ODexRewriterModule$1$1.getInstructions(DexUtil.java:505)
    ...(Skip 22 traces)
    at org.jf.dexlib2.immutable.ImmutableDexFile.of(ImmutableDexFile.java:62)
    at org.rh.smaliex.DexUtil$ODexRewriter.rewriteDexFile(DexUtil.java:435)
    at org.rh.smaliex.DexUtil.odex2dex(DexUtil.java:152)
    at org.rh.smaliex.Main.mainImpl(Main.java:120)
    at org.rh.smaliex.Main.main(Main.java:42)

... (more errors follow) ...
```

I tested the new deodexer with Samsung 4.3, Samsung 6.0.1, and Nexus 7.1.2 dumps to be sure, and they all get deodexed fine.

I'm guessing this is because `oat2dex` can't fully grok Lollipop odex files, so until it's updated for compatibility with Lollipop's oat (version 45), you'll have to find another deodexer.

**Comment by kozross** [comment]
Thank you for that - would you be able to suggest any that can be used for Lollipop odex files?

**Comment by jareddantis** [comment]
I've heard good things about [SuperR's Kitchen](https://forum.xda-developers.com/apps/superr-kitchen/kitchen-superr-s-kitchen-v1-1-50-v2-1-6-t3597434), though I haven't tested it myself.
