### ISSUE TITLE
unable to decompile

### ISSUE THREAD

**Issue by coderstory** [aureljared/simple-deodexer#6]
android 8.0   miui system

Deodexing /app
- AnalyticsCore.apk
  * baksmaling oat/arm64/AnalyticsCore.vdex
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedFileTypeException: oat\arm64\AnalyticsCore.vdex is not an apk, dex, odex or oat file.
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:135)
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:144)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:161)
        at org.jf.baksmali.Main.main(Main.java:102)

  ! unable to decompile oat/arm64/AnalyticsCore.vdex

**Comment by nguyenhai97** [comment]
I have same problem too, I'm using Sony xperia xa1 plus, android 8.0 please add support for vdex file
